name: Call PHP API

on:
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to API
        env:
          API_URL: "http://rikum.starfree.jp/ContactForm/api.php"
        run: |
          curl -X POST https://notify-api.line.me/api/notify \
          //curl -X POST $API_URL \
          //-H "Content-Type: application/json" \
          //-d '{"isNotification" : true, "isStorage" : false, "name": "山田 太郎", "message": "こんにちは。お問い合わせです。"}'