name: Call PHP API

on:
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to API
        env:
          API_URL: "http://rikum.starfree.jp/ContactForm/api.php"
        run: |
          curl -X POST $API_URL \
          -H "Content-Type: application/json" \
          -d '{"key" : "vi01nx92ixn4oprnla", "id": "000001", "user" : "123456", "message": "こんにちは。お問い合わせです。"}'